# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutPath = QtWidgets.QHBoxLayout()
        self.layoutPath.setObjectName("layoutPath")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutPath.addWidget(self.label)
        self.txtPath = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtPath.setFont(font)
        self.txtPath.setObjectName("txtPath")
        self.layoutPath.addWidget(self.txtPath)
        self.cmdGetFile = QtWidgets.QPushButton(self.centralwidget)
        self.cmdGetFile.setObjectName("cmdGetFile")
        self.layoutPath.addWidget(self.cmdGetFile)
        self.cmdGetFolder = QtWidgets.QPushButton(self.centralwidget)
        self.cmdGetFolder.setObjectName("cmdGetFolder")
        self.layoutPath.addWidget(self.cmdGetFolder)
        self.verticalLayout_2.addLayout(self.layoutPath)
        self.cmdStart = QtWidgets.QPushButton(self.centralwidget)
        self.cmdStart.setObjectName("cmdStart")
        self.verticalLayout_2.addWidget(self.cmdStart)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lstPictures = QtWidgets.QListWidget(self.centralwidget)
        self.lstPictures.setObjectName("lstPictures")
        self.verticalLayout.addWidget(self.lstPictures)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdViewPicture = QtWidgets.QPushButton(self.centralwidget)
        self.cmdViewPicture.setEnabled(False)
        self.cmdViewPicture.setObjectName("cmdViewPicture")
        self.horizontalLayout.addWidget(self.cmdViewPicture)
        self.cmdOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.cmdOpenFile.setEnabled(False)
        self.cmdOpenFile.setObjectName("cmdOpenFile")
        self.horizontalLayout.addWidget(self.cmdOpenFile)
        self.cmdOpenMap = QtWidgets.QPushButton(self.centralwidget)
        self.cmdOpenMap.setEnabled(False)
        self.cmdOpenMap.setObjectName("cmdOpenMap")
        self.horizontalLayout.addWidget(self.cmdOpenMap)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "定位图片坐标 Ver.1.1.0全新升级版 【Designed by MoWinCode】"))
        self.label.setText(_translate("MainWindow", "文件（夹）路径："))
        self.cmdGetFile.setText(_translate("MainWindow", "选择文件..."))
        self.cmdGetFolder.setText(_translate("MainWindow", "选择文件夹..."))
        self.cmdStart.setText(_translate("MainWindow", "开始检测"))
        self.label_2.setText(_translate("MainWindow", "搜索到【带GPS坐标】的图片文件："))
        self.cmdViewPicture.setText(_translate("MainWindow", "预览选中图片"))
        self.cmdOpenFile.setText(_translate("MainWindow", "资源管理器中显示选中图片"))
        self.cmdOpenMap.setText(_translate("MainWindow", "浏览器中打开选中图片地理坐标"))
import sourse_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
